<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->partial('layout/head'); ?>
</head>

<body>
<div class='body_head'>
	<?php echo $this->partial('layout/admin-toolbar', array('toolbar' => $this->toolbar, 'remoteSiteId' => $this->remoteSiteId));?>
</div>

<div class='body_action'>
	<?php echo $this->brickViewList['body_action'] ?>
</div>

<div class='body_action_frame'>
	<?=$this->layout()->content ?>
</div>

<div class='footer'>
	<hr />
	<div class='power'>
		powered by <a href='http://www.enorange.com'>Enorange Ltd</a>
	</div>
</div>
</body>

<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/jquery.ndd.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/ckeditor4/ckeditor.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/brick/toolbar/toolbar.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/brick/action-menu/action-menu.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/tab/tab.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('extUrl')?>/prompt/prompt.js"></script>
<script type="text/javascript" src="<?=$this->siteConfig('libUrl')?>/script/icon-selector.js"></script>
<!-- script type="text/javascript" src="<?=$this->siteConfig('libUrl')?>/script/ckeditor.js"></script -->
<? echo $this->headScript() ?>
</html>