<form name='location'>
	<select id='provinceSelector' name='provice'>
		<option value='0'>请选择</option>
		<option value="110000">北京市</option>
		<option value="120000">天津市</option>
		<option value="130000">河北省</option>
		<option value="140000">山西省</option>
		<option value="150000">内蒙古自治区</option>
		<option value="210000">辽宁省</option>
		<option value="220000">吉林省</option>
		<option value="230000">黑龙江省</option>
		<option value="310000">上海市</option>
		<option value="320000">江苏省</option>
		<option value="330000">浙江省</option>
		<option value="340000">安徽省</option>
		<option value="350000">福建省</option>
		<option value="360000">江西省</option>
		<option value="370000">山东省</option>
		<option value="410000">河南省</option>
		<option value="420000">湖北省</option>
		<option value="430000">湖南省</option>
		<option value="440000">广东省</option>
		<option value="450000">广西壮族自治区</option>
		<option value="460000">海南省</option>
		<option value="500000">重庆市</option>
		<option value="510000">四川省</option>
		<option value="520000">贵州省</option>
		<option value="530000">云南省</option>
		<option value="540000">西藏自治区</option>
		<option value="610000">陕西省</option>
		<option value="620000">甘肃省</option>
		<option value="630000">青海省</option>
		<option value="640000">宁夏回族自治区</option>
		<option value="650000">新疆维吾尔自治区</option>
		<option value="710000">台湾省</option>
		<option value="810000">香港特别行政区</option>
		<option value="820000">澳门特别行政区</option>
	</select>
	<select id='citySelector' name='city'>
		<option value='0'>请选择</option>
	</select>
	<select id='countySelector' name='county'>
		<option value='0'>请选择</option>
	</select>
	<br />
	<input type='text' name='addressDetail' value='' />
	<br />
	<input type='text' name='latlon' value=''>
</form>

<ul class='location-list'>

</ul>

<script data-main="<?=$this->siteConfig('libUrl')?>/location-admin/script/app/location" src="<?=$this->siteConfig('extUrl')?>/require-jquery.js"></script>

<script type="text/template" id="location-row">
	<div>
		<div></div>
		<div>
			<div>{{fullAddress}}</div>
			<div>{{latlon}}</div>
		</div>
		<div class='remove'>XX</div>
	</div>
</script>

<script type='text/javascript'>
var addressApi = "http://api.eo.test/rest/address/";
var provinceSelector = $('#provinceSelector');
var citySelector = $('#citySelector');
var countySelector = $('#countySelector');

provinceSelector.change(function() {
	var apiUrl = addressApi + $(this).val();
	
	$.ajax({
		dataType: "json",
		url: apiUrl,
		success: function(jsonObj) {
			citySelector.empty();
			citySelector.append("<option value='0'>请选择</option>");
			countySelector.empty();
			countySelector.append("<option value='0'>请选择</option>");
			_.each(jsonObj.Data, function(dataRow) {
				citySelector.append("<option value='" + dataRow.cityId + "'>" + dataRow.city + "</option>");
			});
		}
	});
});

citySelector.change(function() {
	var apiUrl = addressApi + $(this).val();
	
	$.ajax({
		dataType: "json",
		url: apiUrl,
		success: function(jsonObj) {
			countySelector.empty();
			countySelector.append("<option value='0'>请选择</option>");
			_.each(jsonObj.Data, function(dataRow) {
				countySelector.append("<option value='" + dataRow.countyId + "'>" + dataRow.county + "</option>");
			});
		}
	});
});
</script>