<?php $this->headLink()->appendStylesheet($this->siteConfig('libUrl').'/message/style/message.css'); ?>
<div class='messageform-stage'>
	<div class='messageform-control'>
		<ul class='tabs'>
			<li><a href='#basic'>Basic Info</a></li>
			<li><a href='#element-editor'>Element Info</a></li>
		</ul>
		<div id='basic'>
			<div class='section-title'>表单属性</div>
			<div id='message-form-editor'></div>
			<div class='section-title'>添加选项</div>
			<ul id='element-library'>
				<li class='element-item' data-type='text' data-label='单行文本输入框'>
					<div class='icon' style="background-position:-24px 0px;"></div>
					<div class='text'>文本框</div>
				</li>
				<li class='element-item' data-type='textarea' data-label='文本域'>
					<div class='icon' style="background-position:-72px 0px;"></div>
					<div class='text'>文本域</div>
				</li>
				<li class='element-item' data-type='select' data-label='单选下拉框'>
					<div class='icon' style="background-position:-120px 0px;"></div>
					<div class='text'>下拉框</div>
				</li>
				<li class='element-item' data-type='multicheckbox' data-label='多项勾选框'>
					<div class='icon' style="background-position:-96px 0px;"></div>
					<div class='text'>多选框</div>
				</li>
				<li class='element-item' data-type='radio' data-label='单选按钮'>
					<div class='icon' style="background-position:-48px 0px;"></div>
					<div class='text'>单选框</div>
				</li>
				<li class='element-item' data-type='section' data-label='文本分割符'>
					<div class='icon' style="background-position:-48px -24px;"></div>
					<div class='text'>分割线</div>
				</li>
			</ul>
		</div>
		<div id='element-editor'>
			
		</div>
	</div>
	<div class='messageform-display'>
		<div id='message-form'></div>
		<ul id='element-collection'></ul>
	</div>
</div>

<script data-main="<?=$this->siteConfig('libUrl')?>/message/script/app/message-form" src="<?=$this->siteConfig('extUrl')?>/require-jquery.js"></script>

<script>
var MESSAGE_FORM_ID = "<?php echo $this->messageFormId ?>";

$('.messageform-control').tabs();
$('#element-collection').sortable({placeholder: "ui-state-highlight"}).disableSelection();
</script>

<script type='text/template' id='message-form-editor-template'>
<dl>
	<dt>表单名</dt>
	<dd><input class='mf-editor-label attribute-field' type='text' name='label' value='<%=label%>' /></dd>
	<dt>表单说明</dt>
	<dd><textarea class='mf-editor-description attribute-field' name='description'><%=description%></textarea></dd>
</dl>
</script>
<script type='text/template' id='message-form-template'>
	<div class='label'><%=label%></div>
	<div class='description'><%=description%></div>
</script>

<script type='text/template' id='element-editor-template'>
<div class='section-title'>元素属性</div>
<dl>
	<dt>标题</dt>
	<dd><input class='attribute-field' type="text" name="label" value="<%= label %>" /></dd>
<%
if(type == 'radio' || type == 'select' || type == 'multicheckbox') {
%>
	<dt>候选项：</dt>
	<dd>
	<ul class='option-container'>

	</ul>
	</dd>
<%
}
%>
	<dt>说明</dt>
	<dd><textarea class='attribute-field' name="description"><%= description %></textarea></dd>
	<dt>Class Name</dt>
	<dd><input class='attribute-field' type="text" name="classNames" value="<%= classNames %>" /></dd>
</dl>
<div class='el-action-container'>
	<a class='ui-state-error ui-corner-all el-remove-button' href='#' >
		<div class='ui-icon ui-icon-minusthick el-remove'></div>
		<div class='label'>删除</div>
	</a>
</div>
</script>
<script type='text/template' id='element-template'>
	<div class='element-label'><%= label %></div>
	<div class='element'>
<%
switch(type) {
	case 'text':
%>
			<input type='text' disabled='disabled' />
<%
	break;
	case 'textarea':
%>
			<textarea disabled='disabled'></textarea>
<%
	break;
	case 'radio':
		for(idx in options) {
%>
			<input type='radio' disabled='disabled' name='' value=''><label><%= options[idx].label %></label>
<%
		}
	break;
	case 'multicheckbox':
		for(idx in options) {
%>
			<input type='checkbox' disabled='disabled' name='' value=''><label><%= options[idx].label %></label>
<%
		}
	break;
	case 'select':
%>
			<select disabled='disabled' style='width:100px'></select><br />
<%
	for(idx in options) {
%>
			<label><%= options[idx].label %></label>
<%
		}
	break;
	case 'button':
%>
			<input type='submit' name='button' id='button' value='<%= label %>' /></a>
<%
	break;
	case 'label':
%>
			<hr style='width: 80%' />
<%
	break;
	case 'brand':
%>
		<select disabled='disabled' style='width:100px'><option value='brand'>BRAND</option></select>

<%
	break;
}
%>
		</div>
		<div class='element-desc'><%= description %></div>
</script>

<script type='text/template' id='option-editor-template'>
	<input class='op-input' type='text' group-tag='option' data-code='<%= code %>' name='label' value='<%= label %>' />
	<div class='ui-icon ui-icon-plus op-add'></div>
	<div class='ui-icon ui-icon-minus op-remove'></div>
</script>