<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class CmsDocumentArticleHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['groupId'])) {
            $value = $data['groupId'];
            $return = (string) $value;
            $this->class->reflFields['groupId']->setValue($document, $return);
            $hydratedData['groupId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['label'])) {
            $value = $data['label'];
            $return = (string) $value;
            $this->class->reflFields['label']->setValue($document, $return);
            $hydratedData['label'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['fulltext'])) {
            $value = $data['fulltext'];
            $return = (string) $value;
            $this->class->reflFields['fulltext']->setValue($document, $return);
            $hydratedData['fulltext'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['introicon'])) {
            $value = $data['introicon'];
            $return = (string) $value;
            $this->class->reflFields['introicon']->setValue($document, $return);
            $hydratedData['introicon'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['introtext'])) {
            $value = $data['introtext'];
            $return = (string) $value;
            $this->class->reflFields['introtext']->setValue($document, $return);
            $hydratedData['introtext'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['metakey'])) {
            $value = $data['metakey'];
            $return = (string) $value;
            $this->class->reflFields['metakey']->setValue($document, $return);
            $hydratedData['metakey'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['attachment'])) {
            $value = $data['attachment'];
            $return = $value;
            $this->class->reflFields['attachment']->setValue($document, $return);
            $hydratedData['attachment'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['status'])) {
            $value = $data['status'];
            $return = (string) $value;
            $this->class->reflFields['status']->setValue($document, $return);
            $hydratedData['status'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['publishDate'])) {
            $value = $data['publishDate'];
            if ($value instanceof \MongoDate) { $date = new \DateTime(); $date->setTimestamp($value->sec); $return = $date; } else { $return = new \DateTime($value); }
            $this->class->reflFields['publishDate']->setValue($document, clone $return);
            $hydratedData['publishDate'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['modified'])) {
            $value = $data['modified'];
            if ($value instanceof \MongoDate) { $date = new \DateTime(); $date->setTimestamp($value->sec); $return = $date; } else { $return = new \DateTime($value); }
            $this->class->reflFields['modified']->setValue($document, clone $return);
            $hydratedData['modified'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['modifiedBy'])) {
            $value = $data['modifiedBy'];
            $return = (string) $value;
            $this->class->reflFields['modifiedBy']->setValue($document, $return);
            $hydratedData['modifiedBy'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['modifiedByAlias'])) {
            $value = $data['modifiedByAlias'];
            $return = (string) $value;
            $this->class->reflFields['modifiedByAlias']->setValue($document, $return);
            $hydratedData['modifiedByAlias'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['created'])) {
            $value = $data['created'];
            if ($value instanceof \MongoDate) { $date = new \DateTime(); $date->setTimestamp($value->sec); $return = $date; } else { $return = new \DateTime($value); }
            $this->class->reflFields['created']->setValue($document, clone $return);
            $hydratedData['created'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['createdBy'])) {
            $value = $data['createdBy'];
            $return = (string) $value;
            $this->class->reflFields['createdBy']->setValue($document, $return);
            $hydratedData['createdBy'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['createdByAlias'])) {
            $value = $data['createdByAlias'];
            $return = (string) $value;
            $this->class->reflFields['createdByAlias']->setValue($document, $return);
            $hydratedData['createdByAlias'] = $return;
        }
        return $hydratedData;
    }
}