<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MessageDocumentMessageFormHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['elements']) ? $data['elements'] : null;
        $return = new \Doctrine\ODM\MongoDB\PersistentCollection(new \Doctrine\Common\Collections\ArrayCollection(), $this->dm, $this->unitOfWork, '$');
        $return->setHints($hints);
        $return->setOwner($document, $this->class->fieldMappings['elements']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['elements']->setValue($document, $return);
        $hydratedData['elements'] = $return;

        /** @Field(type="string") */
        if (isset($data['label'])) {
            $value = $data['label'];
            $return = (string) $value;
            $this->class->reflFields['label']->setValue($document, $return);
            $hydratedData['label'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['description'])) {
            $value = $data['description'];
            $return = (string) $value;
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['confirmationOption'])) {
            $value = $data['confirmationOption'];
            $return = (string) $value;
            $this->class->reflFields['confirmationOption']->setValue($document, $return);
            $hydratedData['confirmationOption'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['confirmationText'])) {
            $value = $data['confirmationText'];
            $return = (string) $value;
            $this->class->reflFields['confirmationText']->setValue($document, $return);
            $hydratedData['confirmationText'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['confirmationRedirectUrl'])) {
            $value = $data['confirmationRedirectUrl'];
            $return = (string) $value;
            $this->class->reflFields['confirmationRedirectUrl']->setValue($document, $return);
            $hydratedData['confirmationRedirectUrl'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['confirmationEmail'])) {
            $value = $data['confirmationEmail'];
            $return = (string) $value;
            $this->class->reflFields['confirmationEmail']->setValue($document, $return);
            $hydratedData['confirmationEmail'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['created'])) {
            $value = $data['created'];
            if ($value instanceof \MongoDate) { $date = new \DateTime(); $date->setTimestamp($value->sec); $return = $date; } else { $return = new \DateTime($value); }
            $this->class->reflFields['created']->setValue($document, clone $return);
            $hydratedData['created'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['modified'])) {
            $value = $data['modified'];
            if ($value instanceof \MongoDate) { $date = new \DateTime(); $date->setTimestamp($value->sec); $return = $date; } else { $return = new \DateTime($value); }
            $this->class->reflFields['modified']->setValue($document, clone $return);
            $hydratedData['modified'] = $return;
        }
        return $hydratedData;
    }
}